#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
tmpdir=`mktemp -d $TMPDIR/ledger-XXXXXX`

$DIR/jgit clone amazon-s3://.jgit@bugsplat-git-repos/financials.git $tmpdir

cd $tmpdir

git fsck --strict --full

cd /

rm -rf $tmpdir

echo "Everything looks good!"